# Generated by Django 5.2.15 on 2026-07-06 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramidentity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Telegram identity', 'verbose_name_plural': 'Telegram identities'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Is bot'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='language_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Raw Telegram data'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_identity', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='telegramidentity',
            name='username',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
